---
- hosts: web1
  become: true
  become_method: sudo
  tasks:
  - name: install python3-pip
    apt:
      name: python3-pip
      state: present
  - name: install python3-is-python
    apt:
      name: python3-is-python
      state: present
  - name: install Flask
    pip:
      name: Flask
  - name: create Hello directory
    file:
      path: /var/hello
      state: directory
  - name: copy Hello World starting script
    copy:
      src: hello.sh
      dest: /var/hello/hello.sh
      mode: a+x
  - name: configure Hello as a service
    file:
      path: /etc/init.d/hello
      state: link
      force: yes
      src: /var/hello/hello.sh
  - name: copy Hello World Service
    copy:
      src: hello.py
      dest: /var/hello/hello.py
      mode: a+x
  - name: start Hello
    service:
      name: hello
      enabled: yes
      state: started
